# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faef0da135cd489ff70b134ceee37abfbb4c7c872b6de452e60631df45642de5f182446a64a9e204964aa9991c5ce95c1bc9e2add70c7923d76c440edbe346ed

test:
  secret_key_base: 9e2ee54d0c6aaaff706ede95557eed96cb0f30512b4490603eac5ae98153838dd9bc427d190fe2e320f5a4230ced0ec6cfd3b5264c0a1fe67502c5ff80b8a648

# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  secret_key_base: <%= ENV["STAGING_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["PRODUCTION_SECRET_KEY_BASE"] %>
